import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "./font";
import ClientLayout from "./ClientLayout";

export const metadata: Metadata = {
  title: "VastraDrobe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={[
        geistSans.variable,
        geistMono.variable,
        geistSans.className,
      ].join(" ")}
    >
      <body cz-shortcut-listen="true" className="bg-[#f9fafb]">
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
