import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "./font";
import ClientLayout from "./ClientLayout";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: "VastraDrobe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={[
        geistSans.variable,
        geistMono.variable,
        geistSans.className,
      ].join(" ")}
    >
      <head>
        <link rel="preconnect" href="https://res.cloudinary.com" />
        <link rel="preconnect" href="https://maps.googleapis.com" />
        <link rel="preconnect" href="https://vastradrobe-ims.vercel.app" />
      </head>
      <body cz-shortcut-listen="true" className="bg-[#f9f5ef] overflow-hidden">
        <ClientLayout >{children}</ClientLayout>
        <SpeedInsights />
      </body>
    </html>
  );
}
